export const ROLES = {
  PLATFORM_ADMIN: "PLATFORM_ADMIN",
  SCHOOL_OWNER: "SCHOOL_OWNER",
  PRINCIPAL: "PRINCIPAL",
  VICE_PRINCIPAL: "VICE_PRINCIPAL",
  ADMIN: "ADMIN",
  TEACHER: "TEACHER",
  CLASS_TEACHER: "CLASS_TEACHER",
  STUDENT: "STUDENT",
  PARENT: "PARENT",
  ACCOUNTANT: "ACCOUNTANT",
  TRANSPORT_MANAGER: "TRANSPORT_MANAGER",
  LIBRARIAN: "LIBRARIAN",
  HR: "HR",
};

export default ROLES;